spring.data.mongodb.uri=mongodb+srv://vkcmongousr:m0ng$16@atlascluster.3nyhuvb.mongodb.net/consrecords?appName=AtlasCluster

jwt.secret=cR3c0rDsS3cr3tK3y!Jwt@C0nsRecApp2026#SecureKey
jwt.expiration-ms=86400000