package com.vkc.consultation.records.application.domain.model;

public enum SpecialityType {
    PEDIATRICIAN,
    DEVELOPMENTAL_PEDIATRICIAN,
    CHILD_PSYCHOLOGIST,
    CLINICAL_PSYCHOLOGIST,
    OCCUPATIONAL_THERAPIST,
    SPEECH_LANGUAGE_PATHOLOGIST,
    PHYSIOTHERAPIST,
    SPECIAL_EDUCATOR,
    BEHAVIOR_THERAPIST,
    SOCIAL_WORKER,
    AUDIOLOGIST,
    NUTRITIONIST,
    NEUROLOGIST,
    PSYCHIATRIST
}